### PR TITLE
Added hackathons section

### PR DESCRIPTION
**Pull request by kkkkkabir**
Added a hackathons section.

#### What does this PR do?
I have added a hackathons section where all the coding contests and competition sites will be displayed.

### CODE REVIEW

**Comment by kkkkkabir** [comment]
@saranshkataria Ah! Ok, I got it. Where would Devpost fit in then?

**Comment by saranshkataria** [comment]
Not sure. Probably could be a new section for hackathons, or maybe we could rename the "blogs" title to something more generic to incorporate such websites too

**Comment by saranshkataria** [comment]
Let's rename blogs to websites?

**Comment by jordanliu** [comment]
> Not sure. Probably could be a new section for hackathons, or maybe we could rename the "blogs" title to something more generic to incorporate such websites too

+1 for Hackathons.



> Let's rename blogs to websites?

A lot of the headlines need to be organized

**Comment by kkkkkabir** [comment]
@saranshkataria I guess having a separate section for hackathons and competitions would be nice; this way the navigation would be clearer and not cluttered in one section.

**Comment by saranshkataria** [comment]
Sounds good. Let's do it!

**Comment by kkkkkabir** [comment]
Should I create the hackathon section?

**Comment by saranshkataria** [comment]
Yeah, let's do it as a part of this PR itself

**Comment by kkkkkabir** [comment]
Sorry I was busy for a while. Is the new hackathon section looking good?

**Comment by saranshkataria** [comment]
Great! Thanks for your contribution!

**Pull request merged**
