### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
This PR adds some new articles from my personal blog and update the URL of some previous articles.

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
@tvalentius can you review this, please?

**Comment by saranshkataria** [comment]
In my opinion, we should rather add the link to our blogs than linking every post in here.

**Comment by BolajiAyodeji** [comment]
> In my opinion, we should rather add the link to our blogs than linking every post in here. A single link to https://bolajiayodeji.com instead of having multiple blog posts would make more sense.

I agree with this 💯

**Comment by saranshkataria** [comment]
> > In my opinion, we should rather add the link to our blogs than linking every post in here. A single link to https://bolajiayodeji.com instead of having multiple blog posts would make more sense.
> 
> I agree with this 💯

Great. I have created #53 to add the section and you probably can clean yours up as well once that gets merged.

**Comment by BolajiAyodeji** [comment]
> > > In my opinion, we should rather add the link to our blogs than linking every post in here. A single link to https://bolajiayodeji.com instead of having multiple blog posts would make more sense.
> > 
> > 
> > I agree with this 💯
> 
> Great. I have created #53 to add the section and you probably can clean yours up as well once that gets merged.

Got it, thanks.

**Comment by BolajiAyodeji** [comment]
Closing this following the discussion in #53

**Pull request closed without merging**
