### PR TITLE
Optimize README.md

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
#### What does this PR do

This PR converts the lists to a toggle to improve the navigation experience

#### What are the relevant issues this PR belongs to

N/A

#### Any background context you want to add

N/A

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
> This is neat! Why not move the titles inside details so that the arrow is next to the title and not a new line? Also, we can probable remove the contents section if we are doing this since it becomes redundant.

Sounds good to me, I'll make the changes.

**Comment by BolajiAyodeji** [comment]
Made some changes now. We can't preserve headings and still make them toggle summaries without having the new line arrows. So I made all normal texts and moved them to ## Contents. It looks cleaner now.

What do you think @saranshkataria ?

**Comment by saranshkataria** [comment]
Looks cool now. 
Since you deleted the contents now, the [Developer Circles](./DevCGlobalDirectory.md) is missing from the list. I still think that that is okay because we have the directory hyperlink above it. What do you think?

**Comment by BolajiAyodeji** [comment]
> Looks cool now.
> Since you deleted the contents now, the [Developer Circles](./DevCGlobalDirectory.md) is missing from the list. I still think that that is okay because we have the directory hyperlink above it. What do you think?

Yes, I forgot that.
I think we should add it to the navigation menu now, what do you think?

**Comment by BolajiAyodeji** [comment]
We can have it in both locations actually, I'll make some change so you see what I mean.

**Comment by BolajiAyodeji** [comment]
Actually, it's on the navigation already. Just saw it 😄

**Comment by BolajiAyodeji** [comment]
Does it look better @saranshkataria ?

**Comment by saranshkataria** [comment]
I liked not having it. And only having it in the navigation. But that is my opinion. Maybe someone else can chime in too. @tvalentius ?

**Comment by BolajiAyodeji** [comment]
> I liked not having it. And only having it in the navigation. But that is my opinion. Maybe someone else can chime in too. @tvalentius ?

I agree with this, I thought you wanted it outside the navigation since it existed already.

**Comment by BolajiAyodeji** [comment]
I'll remove it and let's see if it looks great!

**Comment by BolajiAyodeji** [comment]
Looks better @saranshkataria ?

**Comment by saranshkataria** [comment]
Perfect!

**Pull request merged**
