### PR TITLE
Added DevC data of Kolkata Region

### PR DESCRIPTION
**Pull request by hervegithub**
#### What does this PR do?
 Hi, this PR add DevC  data of Kolkata Region
#### Any relevant issues this PR addresses? (optional)

#<NUMBER>

#### Any background context you want to add?
My contribution for facebook open source immersion

### CODE REVIEW

**Comment by saranshkataria** [comment]
@hervegithub just don't create the PR's for the sake of open source immersion. The intent was to learn and not just try and get swag by duplicating existing PR's

**Comment by ayanujju** [comment]
The PR didn't got merged yet, even it raised 2 days back. So, I think you(@saranshkataria ) should merge this PR inorder to stop further such actions. Thank you.

**Comment by saranshkataria** [comment]
@ayanujju there are merge conflicts in there, could you please resolve them first?

**Comment by ayanujju** [comment]
Yeah, I have fixed that. Please review it. Thank you.

**Pull request closed without merging**
