### PR TITLE
Update DevCGlobalDirectory.md

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
#### What does this PR do?

Optimize the circles directory list to make the navigation experience easier.

#### Any relevant issues this PR addresses? (optional)

N/A

#### Any background context you want to add?

This PR also update the text **Leads** to **Lead(s)** since we can still have one lead in a circle.

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
> This looks nice. We could also re-order them according to regions and have the regions as headings?

Sounds perfect! Let's do it

**Comment by BolajiAyodeji** [comment]
Does it look better now @saranshkataria?

Please confirm the region naming also.

**Comment by BolajiAyodeji** [comment]
> Instead of having DevC [Add yours here] under every region, one can be put at the very bottom since it is just a template. Maybe even have the heading as template for it?

Okay, let's try this.

**Comment by BolajiAyodeji** [comment]
Looks good now?

**Comment by saranshkataria** [comment]
LGTM!

**Comment by saranshkataria** [comment]
Great work with all these recent changes

**Pull request merged**
