### PR TITLE
added blogs section

### PR DESCRIPTION
**Pull request by saranshkataria**
#### What does this PR do
Adds a blogs section

#### What are the relevant issues this PR belongs to

discussion on #36

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
Still, making any change @saranshkataria ?

**Comment by saranshkataria** [comment]
@BolajiAyodeji I can clean up the remaining ones too, or if you want to raise a separate PR for it, I am good with that as well. Let me know.

**Comment by BolajiAyodeji** [comment]
> @BolajiAyodeji I can clean up the remaining ones too, or if you want to raise a separate PR for it, I am good with that as well. Let me know.

Please go ahead, I'll close the previous PR!

**Comment by saranshkataria** [comment]
@BolajiAyodeji sounds good. Is there a description that you would like to be added for your site?

**Comment by BolajiAyodeji** [comment]
> @BolajiAyodeji sounds good. Is there a description that you would like to be added for your site?

You can use *Web development, JavaScript and JAMstack blog posts.*

**Comment by saranshkataria** [comment]
Cool. I am done with the cleanup. Ready for review.

**Comment by saranshkataria** [comment]
@BolajiAyodeji I think the person merging PR's should also delete the branches if they are created directly on the repo by us. This would keep things cleaner in the long run :)

**Comment by BolajiAyodeji** [comment]
> @BolajiAyodeji I think the person merging PR's should also delete the branches if they are created directly on the repo by us. This would keep things cleaner in the long run :)

Got it, thanks for the tip!

**Pull request merged**
