### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
#### What does this PR do?
This PR updates the contributor's docs to ensure all PR's follow some unified guidelines.

#### Any relevant issues this PR addresses? (optional)

#63 

#### Any background context you want to add?
N/A

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
Do you think we should cover any sort of guide here?

Also is the ## Guidelines name perfect?

**Comment by saranshkataria** [comment]
@BolajiAyodeji another thing to think about is: do we add people's profiles whose GitHub link is not there? This was more for GitHub profiles, and the names of leads can be seen on the global listing website anyway?

**Comment by BolajiAyodeji** [comment]
@saranshkataria I think we can still leave their names still. Every lead should have a GitHub or GitLab account already, so we might deal with less PR's without GitHub profiles (+ the docs already shows that it is required).

**Comment by saranshkataria** [comment]
@BolajiAyodeji I see a few PR's of people just adding the names. And a lot of these are not leads adding them, it's community members. So they might not know the github profiles I guess. Maybe we should make it explicit to add github profile links, and not merge PRs if it doesn't have them?

**Comment by BolajiAyodeji** [comment]
@saranshkataria I agree with you on this now. Let's do it!

**Comment by BolajiAyodeji** [comment]
Would you want me to make any more changes to the guideline? I think it's clear enough that we want them to include GitHub only.

**Comment by saranshkataria** [comment]
I was thinking of rewording it like : Lead(s) name(s) should be linked to their GitHub account and not their Facebook account

On second thought, it might be a bit redundant

**Pull request merged**
